data = [
{"name":"Cristiano Ronaldo","followers":629,"description":"Footballer","country":"Portugal"},
{"name":"Lionel Messi","followers":505,"description":"Footballer","country":"Argentina"},
{"name":"Selena Gomez","followers":430,"description":"Singer and actress","country":"USA"},
{"name":"Kylie Jenner","followers":400,"description":"Reality TV star and businesswoman","country":"USA"},
{"name":"Dwayne Johnson","followers":395,"description":"Actor and former wrestler","country":"USA"},
{"name":"Ariana Grande","followers":380,"description":"Singer and actress","country":"USA"},
{"name":"Kim Kardashian","followers":364,"description":"Reality TV star and entrepreneur","country":"USA"},
{"name":"Beyonce","followers":320,"description":"Singer and performer","country":"USA"},
{"name":"Khloe Kardashian","followers":311,"description":"Reality TV personality","country":"USA"},
{"name":"Nike","followers":306,"description":"Sportswear brand","country":"USA"},
{"name":"Justin Bieber","followers":294,"description":"Singer","country":"Canada"},
{"name":"Kendall Jenner","followers":292,"description":"Model and TV personality","country":"USA"},
{"name":"Taylor Swift","followers":283,"description":"Singer-songwriter","country":"USA"},
{"name":"National Geographic","followers":282,"description":"Science and nature media","country":"USA"},
{"name":"Virat Kohli","followers":270,"description":"Cricketer","country":"India"},
{"name":"Jennifer Lopez","followers":253,"description":"Singer and actress","country":"USA"},
{"name":"Nicki Minaj","followers":229,"description":"Rapper","country":"USA"},
{"name":"Kourtney Kardashian","followers":223,"description":"Reality TV personality","country":"USA"},
{"name":"Miley Cyrus","followers":215,"description":"Singer and actress","country":"USA"},
{"name":"Neymar","followers":219,"description":"Footballer","country":"Brazil"},
{"name":"Katy Perry","followers":204,"description":"Singer","country":"USA"},
{"name":"Zendaya","followers":185,"description":"Actress","country":"USA"},
{"name":"Kevin Hart","followers":180,"description":"Comedian and actor","country":"USA"},
{"name":"Cardi B","followers":170,"description":"Rapper","country":"USA"},
{"name":"Demi Lovato","followers":165,"description":"Singer","country":"USA"},
{"name":"LeBron James","followers":160,"description":"Basketball player","country":"USA"},
{"name":"Chris Brown","followers":150,"description":"Singer","country":"USA"},
{"name":"Drake","followers":145,"description":"Rapper","country":"Canada"},
{"name":"Shakira","followers":140,"description":"Singer","country":"Colombia"},
{"name":"Billie Eilish","followers":135,"description":"Singer","country":"USA"},
{"name":"Shraddha Kapoor","followers":92,"description":"Bollywood actress","country":"India"},
{"name":"Priyanka Chopra","followers":92,"description":"Actress","country":"India"},
{"name":"Narendra Modi","followers":91,"description":"Prime Minister of India","country":"India"},
{"name":"Deepika Padukone","followers":80,"description":"Bollywood actress","country":"India"},
{"name":"Alia Bhatt","followers":85,"description":"Bollywood actress","country":"India"},
{"name":"Akshay Kumar","followers":66,"description":"Bollywood actor","country":"India"},
{"name":"Jacqueline Fernandez","followers":68,"description":"Actress","country":"India"},
{"name":"Anushka Sharma","followers":64,"description":"Actress and producer","country":"India"},
{"name":"Ranveer Singh","followers":47,"description":"Bollywood actor","country":"India"},
{"name":"Katrina Kaif","followers":78,"description":"Bollywood actress","country":"India"},
{"name":"Shah Rukh Khan","followers":45,"description":"Bollywood actor","country":"India"},
{"name":"Salman Khan","followers":66,"description":"Bollywood actor","country":"India"},
{"name":"Robert Downey Jr","followers":56,"description":"Actor","country":"USA"},
{"name":"Chris Hemsworth","followers":58,"description":"Actor","country":"Australia"},
{"name":"Tom Holland","followers":67,"description":"Actor","country":"UK"},
{"name":"Emma Watson","followers":73,"description":"Actress","country":"UK"},
{"name":"Gal Gadot","followers":108,"description":"Actress","country":"Israel"},
{"name":"Margot Robbie","followers":30,"description":"Actress","country":"Australia"},
{"name":"Will Smith","followers":65,"description":"Actor","country":"USA"},
{"name":"Zac Efron","followers":59,"description":"Actor","country":"USA"},
{"name":"Gigi Hadid","followers":77,"description":"Model","country":"USA"},
{"name":"Bella Hadid","followers":61,"description":"Model","country":"USA"},
{"name":"Hailey Bieber","followers":50,"description":"Model","country":"USA"},
{"name":"Addison Rae","followers":88,"description":"TikTok personality","country":"USA"},
{"name":"Charli DAmelio","followers":44,"description":"TikTok creator","country":"USA"},
{"name":"MrBeast","followers":65,"description":"YouTuber","country":"USA"},
{"name":"PewDiePie","followers":21,"description":"YouTuber","country":"Sweden"},
{"name":"Markiplier","followers":11,"description":"YouTuber","country":"USA"},
{"name":"Logan Paul","followers":27,"description":"YouTuber and boxer","country":"USA"},
{"name":"Jake Paul","followers":26,"description":"YouTuber and boxer","country":"USA"},
{"name":"KSI","followers":13,"description":"YouTuber and boxer","country":"UK"},
{"name":"David Beckham","followers":88,"description":"Footballer","country":"UK"},
{"name":"Ronaldinho","followers":76,"description":"Footballer","country":"Brazil"},
{"name":"Zlatan Ibrahimovic","followers":62,"description":"Footballer","country":"Sweden"},
{"name":"Karim Benzema","followers":74,"description":"Footballer","country":"France"},
{"name":"Sergio Ramos","followers":60,"description":"Footballer","country":"Spain"},
{"name":"Mohamed Salah","followers":63,"description":"Footballer","country":"Egypt"},
{"name":"Kylian Mbappe","followers":120,"description":"Footballer","country":"France"},
{"name":"Erling Haaland","followers":38,"description":"Footballer","country":"Norway"},
{"name":"Rohit Sharma","followers":35,"description":"Cricketer","country":"India"},
{"name":"MS Dhoni","followers":48,"description":"Cricketer","country":"India"},
{"name":"Hardik Pandya","followers":26,"description":"Cricketer","country":"India"},
{"name":"KL Rahul","followers":20,"description":"Cricketer","country":"India"},
{"name":"Suryakumar Yadav","followers":13,"description":"Cricketer","country":"India"},
{"name":"Steve Smith","followers":5,"description":"Cricketer","country":"Australia"},
{"name":"Joe Root","followers":3,"description":"Cricketer","country":"England"},
{"name":"Ben Stokes","followers":2,"description":"Cricketer","country":"England"},
{"name":"Usain Bolt","followers":14,"description":"Olympic sprinter","country":"Jamaica"},
{"name":"Simone Biles","followers":7,"description":"Gymnast","country":"USA"},
{"name":"Michael Phelps","followers":4,"description":"Olympic swimmer","country":"USA"},
{"name":"Lewis Hamilton","followers":39,"description":"F1 driver","country":"UK"},
{"name":"Charles Leclerc","followers":16,"description":"F1 driver","country":"Monaco"},
{"name":"Max Verstappen","followers":12,"description":"F1 driver","country":"Netherlands"},
{"name":"Daniel Ricciardo","followers":9,"description":"F1 driver","country":"Australia"},
{"name":"Sebastian Vettel","followers":3,"description":"F1 driver","country":"Germany"},
{"name":"Rihanna","followers":151,"description":"Singer and entrepreneur","country":"Barbados"},
{"name":"Lady Gaga","followers":57,"description":"Singer and actress","country":"USA"},
{"name":"Bruno Mars","followers":36,"description":"Singer","country":"USA"},
{"name":"Ed Sheeran","followers":45,"description":"Singer-songwriter","country":"UK"},
{"name":"Shawn Mendes","followers":70,"description":"Singer","country":"Canada"},
{"name":"Camila Cabello","followers":65,"description":"Singer","country":"Cuba"},
{"name":"Doja Cat","followers":25,"description":"Singer and rapper","country":"USA"},
{"name":"Travis Scott","followers":54,"description":"Rapper","country":"USA"},
{"name":"Future","followers":23,"description":"Rapper","country":"USA"},
{"name":"Snoop Dogg","followers":83,"description":"Rapper","country":"USA"},
{"name":"Ice Cube","followers":23,"description":"Rapper and actor","country":"USA"},
{"name":"Jackie Chan","followers":40,"description":"Actor and martial artist","country":"Hong Kong"},
{"name":"Jet Li","followers":7,"description":"Martial artist and actor","country":"China"},
{"name":"Arnold Schwarzenegger","followers":26,"description":"Actor and bodybuilder","country":"Austria"},
{"name":"Vin Diesel","followers":102,"description":"Actor","country":"USA"},
{"name":"Jason Statham","followers":38,"description":"Actor","country":"UK"}
]